:images:

  :'bbcnews/fake-sqs':
    :port: 4568
    :name: 'spurious-sqs'

  :'bbcnews/fake-s3':
    :port: 4569
    :name: 'spurious-s3'

  :'smaj/local-dynamo':
    :port: 4570
    :name: 'spurious-dynamo'

  :'smaj/memcached':
    :port: 11211
    :name: 'spurious-memcached'

  :'smaj/fake-elasticache':
    -
      :port: 11212
      :name: 'spurious-elasticache'
      :link: 'spurious-memcached:memcached01'
      :environment:
        :FAKEELASTICACHE_DEFAULT_HOST: '127.0.0.1'
    -
      :from_port: 11212
      :to_port: 11213
      :name: 'spurious-elasticache-internal'
      :link: 'spurious-memcached:memcached01'
